// Generated by CoffeeScript 1.4.0
var index;

index = {
  init: function() {
    this.detectElements();
    return this.bindEvents();
  },
  detectElements: function() {
    return this.remove_buttons = $(".remove");
  },
  bindEvents: function() {
    return this.initRemover();
  },
  initRemover: function() {
    var _this = this;
    return this.remove_buttons.click(function(el) {
      var element;
      element = $(el.currentTarget);
      _this.deleteFeed(element.data("id"));
      return $(element.parents().get(1)).remove();
    });
  },
  deleteFeed: function(id) {
    $.ajax({
      url: SYS.baseUrl + 'admin/dashboard/delete',
      data: $.param({
        id: id
      }),
      type: 'POST',
      dataType: 'json'
    });
    return false;
  }
};

$(document).ready(function() {
  return index.init();
});
